# roles/pxeserver/tasks/main.yml
---

- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: pxeserver_packages
  tags: pxeserver

- name: Ensure services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: pxeserver_services
  tags: pxeserver
