# roles/pxeserver/handlers/main.yml
---

- name: restart nfs
  service:
    name: nfs
    state: restarted
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" and ansible_distribution_major_version < '6'

- name: restart nfs
  systemd:
    name: nfs
    state: restarted
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" and ansible_distribution_major_version > '6'